import type { OpencodeClient } from "@opencode-ai/sdk";
import type { Reviewer, ReviewResult, OrchestratorOptions, CoordinatorResult } from "./types.js";

const activeSessions = new Set<string>();

const DEFAULT_COORDINATOR_PROMPT = `你是一个代码审查协调员。以下审查由独立的专家 reviewer 生成。
你的任务是整合为一个去重后的综合报告。

You are a code review coordinator. The reviews below were generated by independent expert reviewers.
Your task is to synthesize them into a single deduplicated report.

规则 / Rules：
1. 跨 reviewer 去重（同一问题只提一次）/ Deduplicate across reviewers (mention each issue only once)
2. 交叉验证：至少 2 个 reviewer 同意的问题标记为"已确认" / Cross-validate: mark issues agreed by 2+ reviewers as "confirmed"
3. 冲突时取多数意见 / When conflicts arise, follow majority opinion
4. 保留领域特定见解（如安全发现只来自安全 reviewer）/ Preserve domain-specific insights (e.g., security findings from security reviewer only)
5. 使用最严重发现的决策作为最终决策 / Use the most severe finding as the final decision
6. 只报告当前代码中仍存在的问题 / Only report issues that still exist in the current code
7. 若任一 reviewer 内容标注为"（失败: ...）"或内容为空，该 reviewer 视为缺席——最终决策必须为"不可合并 / CANNOT MERGE"，并在阻塞项注明缺失的 reviewer 名称 / If any reviewer's content shows "（失败: ...）" (failed) or is empty, that reviewer counts as missing — the final decision MUST be "CANNOT MERGE" and the missing reviewer name(s) MUST be listed under Blocking Issues

以下是各 reviewer 的审查结果：

{{REVIEWS}}

输出格式 / Output format（中文或英文，取决于语言设置 / in Chinese or English depending on language setting）：
- 第一行：最终决策（可合并 / CAN MERGE、有条件合并 / CONDITIONAL MERGE、不可合并 / CANNOT MERGE）
- 然后简要总结
- "阻塞项" / "Blocking Issues"列出合并前必须修复的问题；如无，写"阻塞项：无" / "Blocking Issues: None"
- "警告项" / "Warnings"列出强烈建议修复但不阻断合并的问题；如无，写"警告项：无" / "Warnings: None"
- "建议项" / "Suggestions"列出非阻塞改进建议；如无，写"建议项：无" / "Suggestions: None"

重要：每个分类必须使用以下精确标题格式 / IMPORTANT: Each category MUST use these exact heading formats:
- ### 🔴 阻塞项 / Blocking Issues
- ### 🟡 警告项 / Warnings
- ### 🟢 建议项 / Suggestions

IMPORTANT: Never use #N format (e.g. #1, #2) to number items in your output. GitHub auto-converts #N to issue/PR references. Use 1. 2. 3. or - list format instead. 请勿使用 #N 格式编号，GitHub 会将其转为 issue/PR 引用。`;

function extractText(messages: Array<{ info: { role: string }; parts: Array<{ type: string; text?: string }> }>): string {
  return messages
    .filter((m) => m.info.role === "assistant")
    .flatMap((m) => m.parts.filter((p): p is { type: "text"; text: string } => p.type === "text"))
    .map((p) => p.text)
    .join("\n");
}

function buildReviewerPrompt(
  reviewerPrompt: string,
  prDiff: string,
  previousContextText?: string,
): string {
  const parts: string[] = [];
  if (previousContextText) {
    parts.push(previousContextText);
    parts.push("=== Current review request ===");
    parts.push(
      "This is a re-review of the same PR. Focus on the CURRENT diff below. " +
      "Do not re-report issues that have already been fixed.",
    );
    parts.push("");
  }
  parts.push(reviewerPrompt);
  parts.push("");
  parts.push("PR Diff:");
  parts.push("```");
  parts.push(prDiff);
  parts.push("```");
  return parts.join("\n");
}

function withTimeout<T>(promise: Promise<T>, ms: number, label: string): Promise<T> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  return Promise.race([
    promise,
    new Promise<never>((_, reject) => {
      timer = setTimeout(() => reject(new Error(`${label} timed out after ${ms}ms`)), ms);
    }),
  ]).finally(() => { if (timer !== undefined) clearTimeout(timer); });
}

export async function runParallelReviewers(
  client: OpencodeClient,
  reviewers: Reviewer[],
  prDiff: string,
  opts: OrchestratorOptions,
): Promise<ReviewResult[]> {
  const deadline = Date.now() + opts.globalTimeoutMs;

  const promises = reviewers.map(async (reviewer) => {
    let sessionId: string | undefined;
    try {
      const remaining = () => Math.max(30_000, deadline - Date.now());
      const resumedFrom = opts.existingSessions?.get(reviewer.name);
      if (resumedFrom) {
        console.log(`[${reviewer.name}] Resuming existing session ${resumedFrom} (timeout: ${remaining()}ms)...`);
        sessionId = resumedFrom;
      } else {
        console.log(`[${reviewer.name}] Starting review (timeout: ${remaining()}ms)...`);
        const sessionResult = await withTimeout(
          client.session.create({ throwOnError: true }),
          remaining(),
          reviewer.name,
        );
        sessionId = sessionResult.data.id;
      }
      activeSessions.add(sessionId);

      const promptResult = await withTimeout(
        client.session.prompt({
          path: { id: sessionId },
          body: {
            parts: [{ type: "text", text: buildReviewerPrompt(reviewer.prompt, prDiff, opts.previousContextText) }],
          },
          throwOnError: true,
        }),
        remaining(),
        reviewer.name,
      );

      const messagesResult = await withTimeout(
        client.session.messages({ path: { id: sessionId }, throwOnError: true }),
        remaining(),
        reviewer.name,
      );
      const messages = messagesResult.data;
      const content = extractText(messages);
      const info = promptResult.data?.info;
      const cost = info?.cost;
      const tokens = info?.tokens;

      if (cost !== undefined) {
        console.log(`[${reviewer.name}] Review complete (${content.length} chars, cost=$${cost.toFixed(4)})`);
      } else {
        console.log(`[${reviewer.name}] Review complete (${content.length} chars, no cost data)`);
      }

      return { reviewer: reviewer.name, content, success: true, cost, tokens, messages, sessionID: sessionId };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`[${reviewer.name}] Failed: ${msg}`);
      return { reviewer: reviewer.name, content: "", success: false, error: msg, sessionID: sessionId };
    } finally {
      if (sessionId && !opts.skipSessionCleanup) {
        activeSessions.delete(sessionId);
        try { await client.session.delete({ path: { id: sessionId } }); } catch { /* ignore */ }
      }
      // skipSessionCleanup: leave the sessionID in activeSessions so the
      // caller can call cleanupAllSessions() after `opencode export` runs.
      // The caller's responsibility to either export+cleanup or let it
      // leak (acceptable for short-lived action runners).
    }
  });

  return Promise.all(promises);
}


export async function runCoordinator(
  client: OpencodeClient,
  reviews: ReviewResult[],
  opts: OrchestratorOptions,
): Promise<CoordinatorResult> {
  const reviewsText = reviews
    .map((r) => `## ${r.reviewer}\n${r.success ? r.content : `（失败: ${r.error}）`}`)
    .join("\n\n---\n\n");

  const promptTemplate = opts.coordinatorPrompt || DEFAULT_COORDINATOR_PROMPT;
  const fullPrompt = promptTemplate.split("{{REVIEWS}}").join(reviewsText);

  let sessionId: string | undefined;
  try {
    const resumedFrom = opts.existingSessions?.get("coordinator");
    if (resumedFrom) {
      console.log(`[coordinator] Resuming existing session ${resumedFrom}...`);
      sessionId = resumedFrom;
    } else {
      const sessionResult = await withTimeout(
        client.session.create({ throwOnError: true }),
        opts.coordinatorTimeoutMs,
        "coordinator",
      );
      sessionId = sessionResult.data.id;
    }
    activeSessions.add(sessionId);

    console.log("[coordinator] Starting synthesis...");

    const promptResult = await withTimeout(
      client.session.prompt({
        path: { id: sessionId },
        body: { parts: [{ type: "text", text: fullPrompt }] },
        throwOnError: true,
      }),
      opts.coordinatorTimeoutMs,
      "coordinator",
    );

    const messagesResult = await withTimeout(
      client.session.messages({ path: { id: sessionId }, throwOnError: true }),
      opts.coordinatorTimeoutMs,
      "coordinator",
    );
    const messages = messagesResult.data;
    const content = extractText(messages);
    const info = promptResult.data?.info;
    const cost = info?.cost;
    const tokens = info?.tokens;

    if (cost !== undefined) {
      console.log(`[coordinator] Synthesis complete (${content.length} chars, cost=$${cost.toFixed(4)})`);
    } else {
      console.log(`[coordinator] Synthesis complete (${content.length} chars, no cost data)`);
    }

    return { content, cost, tokens, messages, sessionID: sessionId };
  } finally {
    if (sessionId && !opts.skipSessionCleanup) {
      activeSessions.delete(sessionId);
      try { await client.session.delete({ path: { id: sessionId } }); } catch { /* ignore */ }
    }
    // skipSessionCleanup: leave the sessionID in activeSessions so the
    // caller can call cleanupAllSessions() after `opencode export` runs.
  }
}

export function buildReviewerDetails(reviews: ReviewResult[]): string {
  const details = reviews.map((r) => {
    const body = r.success ? r.content : `（审查失败: ${r.error}）`;
    return `<details>\n<summary>${r.reviewer}</summary>\n\n${body}\n\n</details>`;
  });
  return `<details>\n<summary>📋 各 Reviewer 详细审查结果</summary>\n\n${details.join("\n\n")}\n\n</details>`;
}

export async function cleanupAllSessions(client: OpencodeClient): Promise<void> {
  for (const id of activeSessions) {
    try { await client.session.delete({ path: { id } }); } catch { /* ignore */ }
  }
  activeSessions.clear();
}
